Files already downloaded and verified
Files already downloaded and verified
Data:
 - Train Set: ((50000, 3, 32, 32),(50000,)), Range: [0.000, 255.000], Labels: 0,..,9
 - Test Set: ((10000, 3, 32, 32),(10000,)), Range: [0.000, 255.000], Labels: 0,..,9
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    train_loader, test_loader = get_data_loaders(classes_pc=classes_pc, nclients= num_clients,
  File "/home/zqf/projects/FLNONIID/ultils.py", line 317, in get_data_loaders
    split = split_balanced_non_iid(x_train, y_train, n_clients=nclients, n_iid=10)
  File "/home/zqf/projects/FLNONIID/ultils.py", line 387, in split_balanced_non_iid
    clients_split = np.array(clients_split, dtype=object)
ValueError: could not broadcast input array from shape (2500,3,32,32) into shape (2500,)
Data split:
 - Client 0: [232 238 279 251 253 264 239 231 261 252]
 - Client 1: [240 244 273 228 240 244 246 278 245 262]
 - Client 2: [264 276 259 245 250 243 234 219 254 256]
 - Client 3: [257 241 244 258 273 256 252 239 244 236]
 - Client 4: [256 261 246 252 255 239 267 252 220 252]
 - Client 5: [229 252 250 257 255 253 251 254 234 265]
 - Client 6: [247 262 249 244 236 225 259 251 274 253]
 - Client 7: [247 265 253 238 245 266 253 265 235 233]
 - Client 8: [222 246 289 267 242 236 229 268 271 230]
 - Client 9: [280 248 243 251 243 261 216 254 245 259]
 - Client 10: [   0 2356    0    0    0    0    0  144    0    0]
 - Client 11: [   0    0    0    0    0    0 1070    0 1430    0]
 - Client 12: [   0    0    1    0 2499    0    0    0    0    0]
 - Client 13: [ 289    0    0    0    0    0    0    0 2211    0]
 - Client 14: [   0    0 1262    0 1238    0    0    0    0    0]
 - Client 15: [   0    0    0    0 1123    0    0    0    0 1377]
 - Client 16: [   0    0    0    5    0    0    0 2495    0    0]
 - Client 17: [   0    0 2474    0    0   26    0    0    0    0]
 - Client 18: [   0 1848    0    0    0    0    0    0    0  652]
 - Client 19: [   0    0    0    0    0 1113    0 1387    0    0]