2024-05-02 22:07:01,339 INFO    StreamThr :32176 [internal.py:wandb_internal():86] W&B internal server running at pid: 32176, started at: 2024-05-02 22:07:01.339646
2024-05-02 22:07:01,341 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status
2024-05-02 22:07:01,345 INFO    WriterThread:32176 [datastore.py:open_for_write():87] open: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\run-ldqm3yyk.wandb
2024-05-02 22:07:01,345 DEBUG   SenderThread:32176 [sender.py:send():379] send: header
2024-05-02 22:07:01,378 DEBUG   SenderThread:32176 [sender.py:send():379] send: run
2024-05-02 22:07:02,306 INFO    SenderThread:32176 [dir_watcher.py:__init__():211] watching files in: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files
2024-05-02 22:07:02,318 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: check_version
2024-05-02 22:07:02,318 INFO    SenderThread:32176 [sender.py:_start_run_threads():1124] run started: ldqm3yyk with start time 1714658821.341053
2024-05-02 22:07:02,318 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: check_version
2024-05-02 22:07:03,078 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: run_start
2024-05-02 22:07:03,103 DEBUG   HandlerThread:32176 [system_info.py:__init__():26] System info init
2024-05-02 22:07:03,103 DEBUG   HandlerThread:32176 [system_info.py:__init__():41] System info init done
2024-05-02 22:07:03,103 INFO    HandlerThread:32176 [system_monitor.py:start():194] Starting system monitor
2024-05-02 22:07:03,104 INFO    SystemMonitor:32176 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-02 22:07:03,104 INFO    HandlerThread:32176 [system_monitor.py:probe():214] Collecting system info
2024-05-02 22:07:03,111 INFO    SystemMonitor:32176 [interfaces.py:start():190] Started cpu monitoring
2024-05-02 22:07:03,111 INFO    SystemMonitor:32176 [interfaces.py:start():190] Started disk monitoring
2024-05-02 22:07:03,113 INFO    SystemMonitor:32176 [interfaces.py:start():190] Started gpu monitoring
2024-05-02 22:07:03,123 INFO    SystemMonitor:32176 [interfaces.py:start():190] Started memory monitoring
2024-05-02 22:07:03,134 INFO    SystemMonitor:32176 [interfaces.py:start():190] Started network monitoring
2024-05-02 22:07:03,140 DEBUG   HandlerThread:32176 [system_info.py:probe():150] Probing system
2024-05-02 22:07:03,140 DEBUG   HandlerThread:32176 [system_info.py:_probe_git():135] Probing git
2024-05-02 22:07:03,210 DEBUG   HandlerThread:32176 [system_info.py:_probe_git():143] Probing git done
2024-05-02 22:07:03,210 DEBUG   HandlerThread:32176 [system_info.py:probe():198] Probing system done
2024-05-02 22:07:03,210 DEBUG   HandlerThread:32176 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.8.18', 'heartbeatAt': '2024-05-02T14:07:03.140821', 'startedAt': '2024-05-02T14:07:01.322606', 'docker': None, 'cuda': None, 'args': ('--agg_mth', 'ligengwk', '--user', 'gsli'), 'state': 'running', 'program': '.\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'git': {'remote': 'https://github.com/Gengsheng-Li/Non-IID-Robust-Federated-Learning-Algorithms.git', 'commit': '01b67c9a3b3b5e43dc259d69241b4a8f2dc31a35'}, 'email': 'ligengchengucd@163.com', 'root': 'E:/Projects/Non-IID-Robust-Federated-Learning-Algorithms', 'host': 'LAPTOP-G8U7O3JS', 'username': 'RyukiRi', 'executable': 'D:\\Anaconda\\envs\\FLlearner\\python.exe', 'cpu_count': 14, 'cpu_count_logical': 20, 'cpu_freq': {'current': 2300.0, 'min': 0.0, 'max': 2300.0}, 'cpu_freq_per_core': [{'current': 2300.0, 'min': 0.0, 'max': 2300.0}], 'disk': {'/': {'total': 1907.7265586853027, 'used': 990.4948616027832}}, 'gpu': 'NVIDIA GeForce RTX 3080 Ti Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080 Ti Laptop GPU', 'memory_total': 17179869184}], 'memory': {'total': 63.672584533691406}}
2024-05-02 22:07:03,210 INFO    HandlerThread:32176 [system_monitor.py:probe():224] Finished collecting system info
2024-05-02 22:07:03,211 INFO    HandlerThread:32176 [system_monitor.py:probe():227] Publishing system info
2024-05-02 22:07:03,211 DEBUG   HandlerThread:32176 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-05-02 22:07:03,308 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_created():271] file/dir created: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\conda-environment.yaml
2024-05-02 22:07:06,643 DEBUG   HandlerThread:32176 [system_info.py:_save_conda():222] Saving conda packages done
2024-05-02 22:07:06,644 INFO    HandlerThread:32176 [system_monitor.py:probe():229] Finished publishing system info
2024-05-02 22:07:06,656 DEBUG   SenderThread:32176 [sender.py:send():379] send: files
2024-05-02 22:07:06,656 INFO    SenderThread:32176 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-05-02 22:07:06,657 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:06,758 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: python_packages
2024-05-02 22:07:06,759 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: python_packages
2024-05-02 22:07:06,759 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: stop_status
2024-05-02 22:07:06,759 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: stop_status
2024-05-02 22:07:06,762 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-02 22:07:07,320 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\conda-environment.yaml
2024-05-02 22:07:07,321 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_created():271] file/dir created: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\wandb-metadata.json
2024-05-02 22:07:07,321 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_created():271] file/dir created: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\requirements.txt
2024-05-02 22:07:07,369 DEBUG   SenderThread:32176 [sender.py:send():379] send: telemetry
2024-05-02 22:07:07,509 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/federated_learningg/federated_learningg/ldqm3yyk/wandb-metadata.json?Expires=1714745226&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bsxBGNVsd16kmmfdhoUveYxySUVkJ%2BvXKwf3U9f7d1clmvoYd2%2FFCOkCzL3rzAOrmhgu29%2BO0NsAL2edYG8cdzaXUmrbeReiLfo32Aq%2BubLJrJpf846jGcTwhQ9YVVLAgqnvjsu0UzpBnEq0xSdtBqaRM7Ek5QPIMOhYnGj9OEFwy26lycBZoqyEEJ%2BBItKGQG7YmvPtnK0F5RrjA95ZxbAWo7UejboM85r2Ho8JE1WRLKLER5%2BBJombCF64BFylsLS8ZvDcMK8oL3qKsMJaONFvJj%2BC5ei4KGJa4RMPQZJarDURc14xyFdyFtWCzvEFOOBSXxf1mkfEdWPFl58zcQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-02 22:07:07,509 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1567'}
2024-05-02 22:07:07,509 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2771] upload_file response body: 
2024-05-02 22:07:08,324 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_created():271] file/dir created: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:08,963 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/federated_learningg/federated_learningg/ldqm3yyk/wandb-metadata.json?Expires=1714745226&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bsxBGNVsd16kmmfdhoUveYxySUVkJ%2BvXKwf3U9f7d1clmvoYd2%2FFCOkCzL3rzAOrmhgu29%2BO0NsAL2edYG8cdzaXUmrbeReiLfo32Aq%2BubLJrJpf846jGcTwhQ9YVVLAgqnvjsu0UzpBnEq0xSdtBqaRM7Ek5QPIMOhYnGj9OEFwy26lycBZoqyEEJ%2BBItKGQG7YmvPtnK0F5RrjA95ZxbAWo7UejboM85r2Ho8JE1WRLKLER5%2BBJombCF64BFylsLS8ZvDcMK8oL3qKsMJaONFvJj%2BC5ei4KGJa4RMPQZJarDURc14xyFdyFtWCzvEFOOBSXxf1mkfEdWPFl58zcQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-02 22:07:08,963 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1567'}
2024-05-02 22:07:08,963 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2771] upload_file response body: 
2024-05-02 22:07:10,352 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:11,356 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:11,766 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:11,880 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/federated_learningg/federated_learningg/ldqm3yyk/wandb-metadata.json?Expires=1714745226&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bsxBGNVsd16kmmfdhoUveYxySUVkJ%2BvXKwf3U9f7d1clmvoYd2%2FFCOkCzL3rzAOrmhgu29%2BO0NsAL2edYG8cdzaXUmrbeReiLfo32Aq%2BubLJrJpf846jGcTwhQ9YVVLAgqnvjsu0UzpBnEq0xSdtBqaRM7Ek5QPIMOhYnGj9OEFwy26lycBZoqyEEJ%2BBItKGQG7YmvPtnK0F5RrjA95ZxbAWo7UejboM85r2Ho8JE1WRLKLER5%2BBJombCF64BFylsLS8ZvDcMK8oL3qKsMJaONFvJj%2BC5ei4KGJa4RMPQZJarDURc14xyFdyFtWCzvEFOOBSXxf1mkfEdWPFl58zcQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-02 22:07:11,880 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1567'}
2024-05-02 22:07:11,880 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2771] upload_file response body: 
2024-05-02 22:07:11,880 INFO    wandb-upload_0:32176 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\util\ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\util\ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda\envs\FLlearner\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Anaconda\envs\FLlearner\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "D:\Anaconda\envs\FLlearner\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\connection.py", line 782, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\util\ssl_.py", line 470, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\urllib3\util\ssl_.py", line 514, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda\envs\FLlearner\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Anaconda\envs\FLlearner\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "D:\Anaconda\envs\FLlearner\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2791, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2760, in upload_file
    response = self._upload_file_session.put(
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\FLlearner\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-05-02 22:07:12,371 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:16,790 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:16,943 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/federated_learningg/federated_learningg/ldqm3yyk/wandb-metadata.json?Expires=1714745226&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bsxBGNVsd16kmmfdhoUveYxySUVkJ%2BvXKwf3U9f7d1clmvoYd2%2FFCOkCzL3rzAOrmhgu29%2BO0NsAL2edYG8cdzaXUmrbeReiLfo32Aq%2BubLJrJpf846jGcTwhQ9YVVLAgqnvjsu0UzpBnEq0xSdtBqaRM7Ek5QPIMOhYnGj9OEFwy26lycBZoqyEEJ%2BBItKGQG7YmvPtnK0F5RrjA95ZxbAWo7UejboM85r2Ho8JE1WRLKLER5%2BBJombCF64BFylsLS8ZvDcMK8oL3qKsMJaONFvJj%2BC5ei4KGJa4RMPQZJarDURc14xyFdyFtWCzvEFOOBSXxf1mkfEdWPFl58zcQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-02 22:07:16,943 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1567'}
2024-05-02 22:07:16,943 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2771] upload_file response body: 
2024-05-02 22:07:19,388 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:21,755 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-02 22:07:21,770 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: stop_status
2024-05-02 22:07:21,771 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: stop_status
2024-05-02 22:07:22,101 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:26,218 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/federated_learningg/federated_learningg/ldqm3yyk/wandb-metadata.json?Expires=1714745226&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bsxBGNVsd16kmmfdhoUveYxySUVkJ%2BvXKwf3U9f7d1clmvoYd2%2FFCOkCzL3rzAOrmhgu29%2BO0NsAL2edYG8cdzaXUmrbeReiLfo32Aq%2BubLJrJpf846jGcTwhQ9YVVLAgqnvjsu0UzpBnEq0xSdtBqaRM7Ek5QPIMOhYnGj9OEFwy26lycBZoqyEEJ%2BBItKGQG7YmvPtnK0F5RrjA95ZxbAWo7UejboM85r2Ho8JE1WRLKLER5%2BBJombCF64BFylsLS8ZvDcMK8oL3qKsMJaONFvJj%2BC5ei4KGJa4RMPQZJarDURc14xyFdyFtWCzvEFOOBSXxf1mkfEdWPFl58zcQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-02 22:07:26,218 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1567'}
2024-05-02 22:07:26,218 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2771] upload_file response body: 
2024-05-02 22:07:27,909 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:29,458 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:33,349 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:33,499 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:34,499 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\config.yaml
2024-05-02 22:07:35,506 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:36,758 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-02 22:07:36,788 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: stop_status
2024-05-02 22:07:36,788 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: stop_status
2024-05-02 22:07:39,147 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:41,553 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:43,204 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/federated_learningg/federated_learningg/ldqm3yyk/wandb-metadata.json?Expires=1714745226&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bsxBGNVsd16kmmfdhoUveYxySUVkJ%2BvXKwf3U9f7d1clmvoYd2%2FFCOkCzL3rzAOrmhgu29%2BO0NsAL2edYG8cdzaXUmrbeReiLfo32Aq%2BubLJrJpf846jGcTwhQ9YVVLAgqnvjsu0UzpBnEq0xSdtBqaRM7Ek5QPIMOhYnGj9OEFwy26lycBZoqyEEJ%2BBItKGQG7YmvPtnK0F5RrjA95ZxbAWo7UejboM85r2Ho8JE1WRLKLER5%2BBJombCF64BFylsLS8ZvDcMK8oL3qKsMJaONFvJj%2BC5ei4KGJa4RMPQZJarDURc14xyFdyFtWCzvEFOOBSXxf1mkfEdWPFl58zcQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-02 22:07:43,204 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1567'}
2024-05-02 22:07:43,204 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2771] upload_file response body: 
2024-05-02 22:07:43,568 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:44,333 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:45,580 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:47,858 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: partial_history
2024-05-02 22:07:47,861 DEBUG   SenderThread:32176 [sender.py:send():379] send: history
2024-05-02 22:07:47,862 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: summary_record
2024-05-02 22:07:47,874 INFO    SenderThread:32176 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-05-02 22:07:48,604 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_created():271] file/dir created: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\wandb-summary.json
2024-05-02 22:07:49,612 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:49,613 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:51,630 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:07:51,765 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-02 22:07:51,795 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: stop_status
2024-05-02 22:07:51,796 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: stop_status
2024-05-02 22:07:55,096 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:07:57,698 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:00,153 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:03,145 DEBUG   SystemMonitor:32176 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-05-02 22:08:03,146 DEBUG   SenderThread:32176 [sender.py:send():379] send: stats
2024-05-02 22:08:05,433 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:05,750 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:06,779 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-02 22:08:06,824 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: stop_status
2024-05-02 22:08:06,825 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: stop_status
2024-05-02 22:08:11,325 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:11,798 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:15,831 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:16,756 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:18,296 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2767] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/federated_learningg/federated_learningg/ldqm3yyk/wandb-metadata.json?Expires=1714745226&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=bsxBGNVsd16kmmfdhoUveYxySUVkJ%2BvXKwf3U9f7d1clmvoYd2%2FFCOkCzL3rzAOrmhgu29%2BO0NsAL2edYG8cdzaXUmrbeReiLfo32Aq%2BubLJrJpf846jGcTwhQ9YVVLAgqnvjsu0UzpBnEq0xSdtBqaRM7Ek5QPIMOhYnGj9OEFwy26lycBZoqyEEJ%2BBItKGQG7YmvPtnK0F5RrjA95ZxbAWo7UejboM85r2Ho8JE1WRLKLER5%2BBJombCF64BFylsLS8ZvDcMK8oL3qKsMJaONFvJj%2BC5ei4KGJa4RMPQZJarDURc14xyFdyFtWCzvEFOOBSXxf1mkfEdWPFl58zcQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-02 22:08:18,296 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2769] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1567'}
2024-05-02 22:08:18,296 ERROR   wandb-upload_0:32176 [internal_api.py:upload_file():2771] upload_file response body: 
2024-05-02 22:08:21,770 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-02 22:08:21,815 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: stop_status
2024-05-02 22:08:21,816 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: stop_status
2024-05-02 22:08:21,876 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:22,165 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:23,881 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:25,687 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: partial_history
2024-05-02 22:08:25,689 DEBUG   SenderThread:32176 [sender.py:send():379] send: history
2024-05-02 22:08:25,689 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: summary_record
2024-05-02 22:08:25,690 INFO    SenderThread:32176 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-05-02 22:08:25,895 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\wandb-summary.json
2024-05-02 22:08:27,705 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:27,914 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:32,725 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:33,149 DEBUG   SenderThread:32176 [sender.py:send():379] send: stats
2024-05-02 22:08:35,986 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:36,779 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-02 22:08:36,823 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: stop_status
2024-05-02 22:08:36,824 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: stop_status
2024-05-02 22:08:38,221 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:43,296 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:44,067 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:48,340 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:50,115 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:51,767 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-02 22:08:51,829 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: stop_status
2024-05-02 22:08:51,830 DEBUG   SenderThread:32176 [sender.py:send_request():406] send_request: stop_status
2024-05-02 22:08:54,195 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
2024-05-02 22:08:56,166 INFO    Thread-16 :32176 [dir_watcher.py:_on_file_modified():288] file/dir modified: E:\Projects\Non-IID-Robust-Federated-Learning-Algorithms\wandb\run-20240502_220701-ldqm3yyk\files\output.log
2024-05-02 22:08:59,893 DEBUG   HandlerThread:32176 [handler.py:handle_request():146] handle_request: status_report
