Files already downloaded and verified
Files already downloaded and verified
Data:
 - Train Set: ((50000, 3, 32, 32),(50000,)), Range: [0.000, 255.000], Labels: 0,..,9
 - Test Set: ((10000, 3, 32, 32),(10000,)), Range: [0.000, 255.000], Labels: 0,..,9
Data split:
Traceback (most recent call last):
  File "train.py", line 57, in <module>
    train_loader, test_loader = get_data_loaders(classes_pc=classes_pc, nclients= num_clients,
  File "/home/zqf/projects/FLNONIID/ultils.py", line 317, in get_data_loaders
    split = split_balanced_non_iid(x_train, y_train, n_clients=nclients, n_iid=10)
  File "/home/zqf/projects/FLNONIID/ultils.py", line 387, in split_balanced_non_iid
    print_split(clients_split)
  File "/home/zqf/projects/FLNONIID/ultils.py", line 381, in print_split
    print(client.shape)
AttributeError: 'tuple' object has no attribute 'shape'